// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bmtech.books.domain;

import com.bmtech.books.domain.UserBook;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserBook_Roo_Configurable {
    
    declare @type: UserBook: @Configurable;
    
}
