// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bmtech.books.domain;

import com.bmtech.books.domain.UserBookDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserBookDataOnDemand_Roo_Configurable {
    
    declare @type: UserBookDataOnDemand: @Configurable;
    
}
